baseURL: "https://nancydaza.github.io/"
title: Nancy A. Daza-Báez
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: Research
          url: research/
          weight: 1
        - name: Teaching
          url: teaching/
          weight: 2
        - name: El Cocuy
          url: personal/
          weight: 3
        - name: CV
          url: cv.pdf
          weight: 4

params:
    description: "Nancy A. Daza-Báez – Research Fellow at the Department of Economics, UCL. Research on intergenerational inequalities, human capital development, health, and gender."
    author: Nancy A. Daza-Báez
    keywords: ["intergenerational mobility","human capital","health economics","gender","inequality","UCL","economics"]
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["research","teaching"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Nancy A. Daza-Báez
          subtitle: "I am a Research Fellow at the Department of Economics at University College London (UCL). My research focuses on intergenerational inequalities, human capital development, health, and gender."
          imageUrl: "picture.jpeg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Research
              url: research/
            - name: Teaching
              url: teaching/

    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:n.baez@ucl.ac.uk
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=JVcNHr0AAAAJ&hl=es
        - name: Twitter
          url: https://x.com/Airedaza
        - name: LinkedIn
          url: https://www.linkedin.com/in/nancy-a-daza-b%C3%A1ez-42840238/

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Nancy A. Daza-Báez"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
