baseURL: "https://nancydaza.github.io/"
title: Nancy A. Daza-Báez
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: Research
          url: papers/
          weight: 1
        - name: Teaching
          url: courses/
          weight: 2
        - name: CV
          url: cv.pdf
          weight: 3

params:
    description: "Nancy A. Daza-Báez – Research Fellow in Economics at UCL. Research on intergenerational inequalities, human capital development, health, and gender."
    author: Nancy A. Daza-Báez
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["papers","courses"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Nancy A. Daza-Báez
          subtitle: "I am a Research Fellow at the Department of Economics at University College London (UCL). My research focuses on intergenerational inequalities, human capital development, health, and gender."
          imageUrl: "picture.jpeg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Research
              url: papers/
            - name: Teaching
              url: courses/
            - name: Tags
              url: tags/

    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:n.baez@ucl.ac.uk
        - name: Google Scholar
          url: https://scholar.google.com/
        - name: Twitter
          url: https://x.com/
        - name: LinkedIn
          url: https://www.linkedin.com/

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Nancy A. Daza-Báez"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
